# Development environment override
services:
  php:
    restart: "no"
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - /app/var/
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      XDEBUG_SESSION: 1
      PHP_IDE_CONFIG: "serverName=api"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###
